extensions: &extensions
    - apcu
    - bcmath
    - bz2
    - calendar
    - gd
    - intl
    - opcache
    - pdo_mysql
    - redis
    - soap
    - sockets
    - xsl
    - zip
    - imap
    - gmp
    - gnupg

dev_composer_packages: &dev_composer_packages
    - sandersander/composer-link
    - franzl/studio
    - sidz/phpstan-rules
    - phpunit/phpunit ^9
    - phpstan/phpstan

environment:
    - dev

versions:
    - version: "8.2"
      suffix: ""
      extensions: [*extensions, [imagick]]
      dev_composer_packages: [*dev_composer_packages]
    - version: "8.3"
      suffix: ""
      extensions: [*extensions, [Imagick/imagick@28f27044e435a2b203e32675e942eb8de620ee58]]
      dev_composer_packages: [*dev_composer_packages]
    - version: "8.4"
      suffix: ""
      extensions: [*extensions, [imagick]]
      dev_composer_packages: [*dev_composer_packages]
