name: "Run PHPStan with ReviewDog"
description: "🐾 Run PHP Static Analyzer with ReviewDog."
author: "Mike Bronner"
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: true
    default: ${{ github.token }}

  level:
    description: "Report level for reviewdog [info,warning,error]"
    required: false
    default: "error"

  reporter:
    description: |
      Reporter of reviewdog command [github-check,github-pr-review].
      Default is github-pr-check.
    required: false
    default: "github-pr-review"

  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog. Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: "any"

  filter_mode:
    description: |
      reviewdog filter results by diff and you can control how reviewdog filter results by -filter-mode flag. Available filter modes are as below.
      added
      Filter results by added/modified lines.
      diff_context (default)
      Filter results by diff context. i.e. changed lines +-N lines (N=3 for example).
    default: "diff_context"

runs:
  using: "composite"
  steps:
    - name: Install PhpStan
      shell: bash
      run: |
        composer require --dev phpstan/phpstan-symfony sidz/phpstan-rules
        bin/console cache:warmup
    - name: 
      shell: bash
      run: |
        chmod +x "$GITHUB_ACTION_PATH/execute.sh"
    - run: $GITHUB_ACTION_PATH/execute.sh
      shell: bash
      env:
        REVIEWDOG_VERSION: v0.20.3
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
        INPUT_DIFF_CONTEXT: ${{ inputs.filter_mode }}
branding:
  icon: "check-circle"
  color: "green"
